from src.adapters.base import DatasetAdapter
from src.adapters.pap import PAPAdapter
from src.adapters.toxicchat import ToxicChatPlainAdapter
from src.adapters.toxicchat_cipher import (
    ToxicChatCipherAdapter,
    ToxicChatObfuscationAdapter,
    ToxicChatBase64Adapter,
    ToxicChatRot13Adapter,
    ToxicChatHexAdapter,
    ToxicChatLeetspeakAdapter,
    ToxicChatCaesarAdapter,
    ToxicChatCesarAdapter,
    create_obfuscated_prompt,
    obfuscate_payload,
    obfuscate_toxicchat_input,
    encode_payload,
    encode_base64,
    encode_rot13,
    encode_hex,
    encode_leetspeak,
    encode_caesar,
    decode_caesar,
)
from src.adapters.toxicchat_prefix import (
    ToxicChatPrefixAdapter,
    ToxicChatForcedAffirmationAdapter,
    ToxicChatTargetedPrefixAdapter,
    create_prefix_prompt,
    inject_prefix_prompt,
    create_forced_affirmation_prompt,
)
from src.adapters.toxicchat_gcg import (
    ToxicChatGCGAdapter,
    ToxicChatUniversalSuffixAdapter,
    create_gcg_prompt,
    DEFAULT_GCG_SUFFIXES,
)
from src.adapters.emoji import EmojiAdapter
from src.adapters.registry import AdapterRegistry, get_adapter

__all__ = [
    "DatasetAdapter",
    "PAPAdapter",
    "EmojiAdapter",
    "ToxicChatPlainAdapter",
    "ToxicChatCipherAdapter",
    "ToxicChatObfuscationAdapter",
    "ToxicChatBase64Adapter",
    "ToxicChatRot13Adapter",
    "ToxicChatHexAdapter",
    "ToxicChatLeetspeakAdapter",
    "ToxicChatCaesarAdapter",
    "ToxicChatCesarAdapter",
    "ToxicChatPrefixAdapter",
    "ToxicChatForcedAffirmationAdapter",
    "ToxicChatTargetedPrefixAdapter",
    "ToxicChatGCGAdapter",
    "ToxicChatUniversalSuffixAdapter",
    "AdapterRegistry",
    "get_adapter",
    "create_obfuscated_prompt",
    "obfuscate_payload",
    "obfuscate_toxicchat_input",
    "encode_payload",
    "encode_base64",
    "encode_rot13",
    "encode_hex",
    "encode_leetspeak",
    "encode_caesar",
    "decode_caesar",
    "create_prefix_prompt",
    "inject_prefix_prompt",
    "create_forced_affirmation_prompt",
    "create_gcg_prompt",
    "DEFAULT_GCG_SUFFIXES",
]
